### PR TITLE
Add pdf result and supplier resource interface

### PR DESCRIPTION
**Pull request by fxmanu**

### CODE REVIEW

**Comment by fxmanu** [comment]
@j-frost please accept this pull request in order to add two more resource interfaces.

**Review by j-frost — CHANGES_REQUESTED** [review]
Missing tests.

**Comment by fxmanu** [comment]
@j-frost sorry. I fixed that :-)

**Comment by j-frost** [comment]
@fxmanu sorry for taking a while on this, had a lot going on. When I execute tests, four of them fail for me. Can you confirm?

**Comment by fxmanu** [comment]
@j-frost no problem. I'll look into this next week.

**Comment by fxmanu** [comment]
@j-frost I took a while on this myself this time. Sorry about this. But finally, I fixed the unit tests :)

**Comment by fxmanu** [comment]
@j-frost seems like you're not working on that project anymore.
I'd still like to use it and to push it forward a bit. If you want, you can give me (Co)-ownership and I can help in maintaining it.

Please let me know.

**Comment by j-frost** [comment]
@fxmanu It's true we're not actively working on this right now. This code does not belong to me personally. I'll get back to you with an answer.

**Comment by fxmanu** [comment]
@j-frost thank you!

**Comment by j-frost** [comment]
@fxmanu I've gotten the go-ahead; will work on this on the weekend 👍

**Comment by fxmanu** [comment]
@j-frost Do you mean that you will continue to work on the project or that you will work on being able to hand it over?

**Comment by j-frost** [comment]
Both @fxmanu :)

**Comment by j-frost** [comment]
Hey @fxmanu I've made some changes; can you re-open this PR on main?

**Pull request closed without merging**
